Add customers resource
Open-Pix/php-sdk pull request #9
Opened 2023-06-07 20:25 UTC by criskell

- configure dependencies
- add request builder
- add request transport
- add paginator
- add costumers list endpoint

2023-06-07 21:17 UTC, edumaciel10 commented on tests/RequestTest.php
> +            ->with("GET", "https://example.com/costumer?skip=100&limit=200");
You are confusing customer with costumer

2023-06-07 21:17 UTC, edumaciel10 requested changes
Fix the customer naming

2023-06-07 21:57 UTC, daniloab commented on src/ApiErrorException.php
> +namespace Openpix\PhpSdk;
use in all places `OpenPix`

2023-06-08 12:32 UTC, daniloab reviewed
you can use this repo as inspiration https://github.com/DanielHe4rt/larapix/ since it is an implementation of our api with php

2023-06-08 19:21 UTC, merged